// <auto-generated />
namespace PassionProjectMVP_Diarra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MVPwithdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MVPwithdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202102180149394_MVPwithdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
